version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DOG_API_BASE_URL=https://dog.ceo/api
      - CORS_ORIGIN=https://breeds-production.up.railway.app/
      - ENABLE_DETAILED_ERRORS=false
      - ENABLE_REQUEST_LOGGING=false
      - LOG_LEVEL=info

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:3001/api
      - VITE_ENABLE_DEBUG=false
      - VITE_SHOW_DETAILED_ERRORS=false
