version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DOG_API_BASE_URL=https://dog.ceo/api
      - CORS_ORIGIN=http://localhost:3000,http://127.0.0.1:3000
      - LOG_LEVEL=info

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://backend:3001/api
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
