version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DOG_API_BASE_URL=https://dog.ceo/api
      - CORS_ORIGIN=http://localhost:3000,http://frontend:3000
      - ENABLE_DETAILED_ERRORS=false
      - ENABLE_REQUEST_LOGGING=false
      - LOG_LEVEL=info

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://backend:3001/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
